### PR TITLE
Bump tabulate

### PR DESCRIPTION
**Pull request by SantanaTiago**
- Bump tabulate version to `^0.9.0`

### CODE REVIEW

**Review by RedRoserade — APPROVED** [review]

**Comment by cau-git** [comment]
Do you understand why `test-build-docs` CI check fails?

**Comment by RedRoserade** [comment]
Seems like poetry is trying to install packages into the root, and it probably doesn't have permission to.

**Comment by RedRoserade** [comment]
You can see that it's skipping the virtualenv creation here: https://github.com/DS4SD/project-mognet/actions/runs/6221020034/job/16883001858?pr=8#step:5:9

**Comment by RedRoserade** [comment]
Try removing this configuration: https://github.com/DS4SD/project-mognet/actions/runs/6221020034/workflow#L12 (`POETRY_VIRTUALENVS_CREATE`)

And on line 28, prepend `poetry run` to the `mkdocs` command.

This will run everything inside a virtual environment, and remove the need for root.

**Review by RedRoserade — APPROVED** [review]

**Comment by RedRoserade** [comment]
@SantanaTiago you will probably need to update the other CI files too: https://github.com/DS4SD/project-mognet/blob/main/.github/workflows/ci.yml#L11

**Comment by RedRoserade** [comment]
@cau-git done, it passes now.

**Review by dolfim-ibm — APPROVED** [review]

**Pull request merged**
